CC = gcc   # compilateur à utiliser

CFLAGS = -Wall -g -pthread     # flags à utiliser (Wall pour tous les warnings)


# On execute tous les fichiers td1

all: final 
	./final    

# On dit à phony que all et clean sont des fonctions pas des fichiers
.PHONY: all clean

# On crée un lien entre des fichiers objets et nos fichiers c
final: final.o
	$(CC) $(CFLAGS) -o final final.o

# On crée nos fichiers objets déjà linkés
final.o: final.c
	$(CC) $(CFLAGS) -c final.c

# On enlève nos objets pour libérer l'espace inutile
clean:
	rm -f *.o final
