CC = gcc   # compilateur à utiliser

CFLAGS = -Wall -g     # flags à utiliser (Wall pour tous les warnings)


# On execute tous les fichiers td1

all: td1 
	./td1    

# On dit à phony que all et clean sont des fonctions pas des fichiers
.PHONY: all clean

# On crée un lien entre des fichiers objets et nos fichiers c
td1: td1.o hello.o
	$(CC) $(CFLAGS) -o td1 td1.o hello.o

# On crée nos fichiers objets déjà linkés
td1.o: td1.c hello.h
	$(CC) $(CFLAGS) -c td1.c

# Pareil
hello.o: hello.c hello.h
	$(CC) $(CFLAGS) -c hello.c

# On enlève nos objets pour libérer l'espace inutile
clean:
	rm -f *.o td1
